import { DomainError } from '../lib.js';

export const transitions = Object.freeze({
  CREATED: ['INITIATED', 'CANCELLED'],
  INITIATED: ['VALIDATING', 'FAILED'],
  VALIDATING: ['RISK_CHECK', 'FAILED'],
  RISK_CHECK: ['ROUTING', 'DECLINED', 'FAILED'],
  ROUTING: ['PROCESSING', 'FAILED'],
  PROCESSING: ['AUTHORIZED', 'PENDING', 'UNKNOWN', 'DECLINED', 'FAILED', 'TIMEOUT'],
  PENDING: ['AUTHORIZED', 'SUCCESS', 'UNKNOWN', 'FAILED', 'EXPIRED'],
  UNKNOWN: ['AUTHORIZED', 'SUCCESS', 'FAILED', 'REVERSED'],
  AUTHORIZED: ['CAPTURED', 'REVERSED', 'EXPIRED', 'FAILED'],
  CAPTURED: ['SUCCESS', 'REVERSED'],
  SUCCESS: ['REFUND_PENDING', 'PARTIALLY_REFUNDED', 'REFUNDED', 'DISPUTED', 'REVERSED', 'RECONCILIATION_PENDING', 'SETTLED'],
  REFUND_PENDING: ['PARTIALLY_REFUNDED', 'REFUNDED', 'SUCCESS', 'FAILED'],
  PARTIALLY_REFUNDED: ['REFUND_PENDING', 'REFUNDED', 'DISPUTED', 'SETTLED'],
  REFUNDED: ['RECONCILIATION_PENDING', 'SETTLED'],
  DISPUTED: ['CHARGEBACK', 'SUCCESS'],
  CHARGEBACK: ['REVERSED', 'SUCCESS'],
  RECONCILIATION_PENDING: ['SETTLED', 'RECONCILIATION_FAILED'],
  RECONCILIATION_FAILED: ['RECONCILIATION_PENDING', 'SETTLED'],
  DECLINED: [], FAILED: ['PROCESSING'], TIMEOUT: ['UNKNOWN'], CANCELLED: [], EXPIRED: [], REVERSED: [], SETTLED: []
});

export function assertTransition(from, to) {
  if (!transitions[from]?.includes(to)) {
    throw new DomainError(`Invalid payment transition: ${from} → ${to}`, 'INVALID_STATE_TRANSITION', 409, { from, to });
  }
}
